apiVersion: v1
name: otomi
description: A Helm chart for installing otomi in Kubernetes
home: https://otomi.io/
icon: https://otomi.io/img/otomi-logo.svg
type: application
version: '1'
appVersion: '0.1.0'
keywords:
  - otomi
  - otomi.io
  - container-management
  - continuous-delivery
  - continuous-deployment
  - continuous-integration
sources:
  - https://github.com/redkubes/otomi-core
