apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "demo-tlspass.fullname" . }}
  labels: {{- include "demo-tlspass.labels" $ | nindent 4 }}
data:
  default.conf: |
    server {
      listen 1337 ssl;

      root /www/otomi;
      index index.html;

      server_name tlspass.team-otomi.{{ .Values.clusterDomainSuffix }};
      ssl_certificate /etc/nginx-server-certs/tls.crt;
      ssl_certificate_key /etc/nginx-server-certs/tls.key;
    }
  index.html: |
    <!doctype html>
    <html lang="en">
    <head>
      <meta charset="utf-8">
      <title>Otomi Demo</title>
    </head>
    <body>
      <center>
        <h2>Welcome to Otomi</h2>
      </center>
    </body>
    </html>  
