{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "demo-tlspass.serviceAccountName" . }}
  labels: {{- include "demo-tlspass.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
---
{{- end }}    