apiVersion: v1
kind: Secret
metadata:
  name: {{ include "demo-tlspass.fullname" . }}
  labels: {{- include "demo-tlspass.labels" $ | nindent 4 }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.tlsCert | b64enc }}
  tls.key: {{ .Values.tlsKey | b64enc }}