apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-tlspass.fullname" . }}
  labels:
    {{- include "demo-tlspass.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.portTls }}
      targetPort: https
      protocol: TCP
      name: https
  selector:
    {{- include "demo-tlspass.selectorLabels" . | nindent 4 }}
