apiVersion: batch/v1
kind: Job
metadata:
  name: otomi-installer-job
spec:
  template:
    metadata:
      name: otomi-install-{{ randAlphaNum 8 }} # FIXME: remove random part
    spec:
      serviceAccountName: {{ .Release.Name }}
      initContainers:
        - name: bootstrap-values
          image: otomi/core:otomi-install-chart # FIXME: fix the tag
          imagePullPolicy: Always
          command: ['/bin/bash', '-c']
          args: [bin/chart-prepare.sh && chmod a+w -R $ENV_DIR]
          env:
            - name: IN_DOCKER
              value: '1'
          volumeMounts:
            - name: otomi-values
              mountPath: /home/app/stack/env
            - name: values-secret
              mountPath: /secret
        - name: map-values
          image: otomi/tasks:otomi-chart # FIXME: go back to correct tag
          imagePullPolicy: Always
          command: ['sh', '-c']
          args: [npm run tasks:otomi-chart -- true]
          env:
            - name: IN_DOCKER
              value: '1'
            - name: OTOMI_VALUES_INPUT
              value: /secret/values.yaml
            - name: OTOMI_ENV_DIR
              value: /env
            - name: OTOMI_SCHEMA_PATH
              value: /env/values-schema.yaml
          volumeMounts:
            - name: otomi-values
              mountPath: /env
            - name: values-secret
              mountPath: /secret
        - name: map-values
          image: otomi/tasks:otomi-chart # FIXME: go back to correct tag
          imagePullPolicy: Always
          command: ['sh', '-c']
          args:
            - |
              echo Merging given values with the bootstrapped value files
              # while true; do sleep 30; done
              npm run tasks:otomi-chart
              echo Done.
          env:
            - name: IN_DOCKER
              value: '1'
            - name: OTOMI_VALUES_INPUT
              value: /secret/values.yaml
            - name: OTOMI_ENV_DIR
              value: /env
            - name: OTOMI_SCHEMA_PATH
              value: /env/values-schema.yaml
          volumeMounts:
            - name: otomi-values
              mountPath: /env
            - name: values-secret
              mountPath: /secret
        - name: bootstrap-values
          # image: otomi/core:master
          image: otomi/core:otomi-install-chart # FIXME: fix the tag
          imagePullPolicy: Always
          command: ['/bin/bash', '-x']
          args:
            - bin/chart-prepare.sh
          env:
            - name: IN_DOCKER
              value: '1'
          volumeMounts:
            - name: otomi-values
              mountPath: /home/app/stack/env
        - name: bootstrap-values
          # image: otomi/core:master
          image: otomi/core:otomi-install-chart # FIXME: fix the tag
          imagePullPolicy: Always
          command: ['/bin/bash', '-x']
          args:
            - bin/chart-prepare.sh
          env:
            - name: IN_DOCKER
              value: '1'
          volumeMounts:
            - name: otomi-values
              mountPath: /home/app/stack/env
      containers:
        - name: otomi-install
          # image: otomi/core:master
          image: otomi/core:otomi-install-chart # FIXME: fix the tag
          imagePullPolicy: Always
          command: [/bin/bash, -x]
          args: [bin/deploy.sh]
          env:
            - name: IN_DOCKER
              value: '1'
            - name: CI
              value: 'true'
            - name: ENV_DIR
              value: /home/app/stack/env
          volumeMounts:
            - name: otomi-values
              mountPath: /home/app/stack/env
      volumes:
        - name: values-secret
          secret:
            secretName: '{{ .Release.Name }}-values'
        - name: otomi-values
          emptyDir: {}
      restartPolicy: Never
