apiVersion: batch/v1
kind: Job
metadata:
  name: otomi-installer-job
spec:
  template:
    metadata:
      name: otomi-install
    spec:
      imagePullSecrets:
      - name: regcred
      serviceAccountName: {{ .Release.Name }}
      initContainers:
        - name: bootstrap-values
          image: otomi/core:{{ .Values.otomi.version }}
          imagePullPolicy: Always
          command: ['/bin/bash', '-c']
          args: 
            - |
              {{ .Files.Get "scripts/bootstrap-values.sh" | nindent 14 }}
          env:
            - name: IN_DOCKER
              value: '1'
            - name: VERBOSE
              value: '1'
            - name: ENV_DIR
              value: /env
            - name: OTOMI_VALUES_INPUT
              value: /secret/values.yaml
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-sops-secrets
          volumeMounts:
            - name: otomi-values
              mountPath: /env
            - name: values-secret
              mountPath: /secret
        - name: map-values
          image: otomi/tasks:otomi-chart # FIXME: tag
          imagePullPolicy: Always
          command: ['sh', '-c']
          args:
            - |
              {{ .Files.Get "scripts/map-values.sh" | nindent 14 }}
          env:
            - name: IN_DOCKER
              value: '1'
            - name: OTOMI_VALUES_INPUT
              value: /secret/values.yaml
            - name: OTOMI_ENV_DIR
              value: /env
            - name: OTOMI_SCHEMA_PATH
              value: /env/values-schema.yaml
          volumeMounts:
            - name: otomi-values
              mountPath: /env
            - name: values-secret
              mountPath: /secret
        - name: encrypt-values
          image: otomi/core:{{ .Values.otomi.version }} # FIXME: tag
          imagePullPolicy: Always
          command: [/bin/bash, -c]
          args:
            - |
              {{ .Files.Get "scripts/encrypt-values.sh" | nindent 14 }}
          env:
            - name: IN_DOCKER
              value: '1'
            - name: VERBOSE
              value: '1'
            - name: CI
              value: 'true'
            - name: ENV_DIR
              value: /env
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-sops-secrets
          volumeMounts:
            - name: otomi-values
              mountPath: /env
      containers:
        - name: otomi-install
          image: otomi/core:{{ .Values.otomi.version }} # FIXME: tag
          imagePullPolicy: Always
          command: [/bin/bash, -c]
          args:
            - |
              {{ .Files.Get "scripts/deploy.sh" | nindent 14 }}
          env:
            - name: IN_DOCKER
              value: '1'
            - name: VERBOSE
              value: '1'
            - name: CI
              value: 'true'
            - name: ENV_DIR
              value: /home/app/stack/env
          envFrom:
            - secretRef:
                name: {{ .Release.Name }}-sops-secrets
          volumeMounts:
            - name: otomi-values
              mountPath: /home/app/stack/env
      volumes:
        - name: values-secret
          secret:
            secretName: '{{ .Release.Name }}-values'
        - name: otomi-values
          emptyDir: {}
      restartPolicy: Never
