apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "otomi.fullname" . }}
  labels: {{- include "otomi.labels" . | nindent 4 }}
spec:
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations: {{- toYaml . | nindent 8 }}
      {{- end }}
      labels: {{- include "otomi.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "otomi.serviceAccountName" . }}
      securityContext: {{- toYaml .Values.podSecurityContext | nindent 8 }}
      initContainers:
        - name: bootstrap-values
          securityContext: {{- toYaml .Values.securityContext | nindent 12 }}
          image: otomi/core:{{ .Values.otomi.version }}
          imagePullPolicy: Always
          command: ['/bin/bash', '-c']
          args: 
            - |
              {{ .Files.Get "scripts/bootstrap-values.sh" | nindent 14 }}
          env:
            - name: IN_DOCKER
              value: '1'
            - name: VERBOSE
              value: '1'
            - name: ENV_DIR
              value: /env
            - name: OTOMI_VALUES_INPUT
              value: /secret/values.yaml
          envFrom:
            - secretRef:
                name: {{ include "otomi.fullname" . }}-sops-secrets
          volumeMounts:
            - name: otomi-values
              mountPath: /env
            - name: values-secret
              mountPath: /secret
        - name: map-values
          image: otomi/tasks:master
          imagePullPolicy: Always
          command: ['sh', '-c']
          args:
            - |
              {{ .Files.Get "scripts/map-values.sh" | nindent 14 }}
          env:
            - name: IN_DOCKER
              value: '1'
            - name: OTOMI_VALUES_INPUT
              value: /secret/values.yaml
            - name: OTOMI_ENV_DIR
              value: /env
            - name: OTOMI_SCHEMA_PATH
              value: /env/values-schema.yaml
          volumeMounts:
            - name: otomi-values
              mountPath: /env
            - name: values-secret
              mountPath: /secret
        - name: encrypt-values
          image: otomi/core:{{ .Values.otomi.version }}
          imagePullPolicy: Always
          command: [/bin/bash, -c]
          args:
            - |
              {{ .Files.Get "scripts/encrypt-values.sh" | nindent 14 }}
          env:
            - name: IN_DOCKER
              value: '1'
            - name: VERBOSE
              value: '1'
            - name: CI
              value: 'true'
            - name: ENV_DIR
              value: /env
          envFrom:
            - secretRef:
                name: {{ include "otomi.fullname" . }}-sops-secrets
          volumeMounts:
            - name: otomi-values
              mountPath: /env
      containers:
        - name: otomi-install
          image: otomi/core:{{ .Values.otomi.version }}
          imagePullPolicy: Always
          command: [/bin/bash, -c]
          args:
            - |
              {{ .Files.Get "scripts/deploy.sh" | nindent 14 }}
          env:
            - name: IN_DOCKER
              value: '1'
            - name: VERBOSE
              value: '1'
            - name: CI
              value: 'true'
            - name: ENV_DIR
              value: /home/app/stack/env
          envFrom:
            - secretRef:
                name: {{ include "otomi.fullname" . }}-sops-secrets
          volumeMounts:
            - name: otomi-values
              mountPath: /home/app/stack/env
      volumes:
        - name: values-secret
          secret:
            secretName: '{{ .Release.Name }}-values'
        - name: otomi-values
          emptyDir: {}
      restartPolicy: Never
