apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-values
  labels: {{- include "otomi.labels" . | nindent 4 }}
type: Opaque
data:
  values.yaml: |-
{{ .Values | toYaml | b64enc | indent 4 }}
