
{{- $v := .Values }}
{{- $ := . }}
{{- $containers := list (dict "isInit" false "container" $v) }}
{{- if $v.init }}{{ $containers = prepend $containers (dict "isInit" true "container" $v.init) }}{{ end }}
{{- range $item := $containers }}
  {{- $c := $item.container }}
  {{- $initSuffix := $item.isInit | ternary "-init" "" }}
  {{- with $c.nativeSecrets }}
apiVersion: v1
kind: Secret
metadata:
  labels: {{- include "jobs.labels" $ | nindent 4 }}
  name: {{ $.Release.Name }}{{ $initSuffix }}
data:
    {{- range $key, $val := . }}
  {{ $key }}: "{{ $val | b64enc }}"
    {{- end }}
---
  {{- end }}
{{- end }}