{{- $v := .Values }}
{{- $provider := $v.kms.sops.provider }}
{{- $sopsEnvTpl := readFile "../helmfile.d/snippets/sops-env.gotmpl" }}
releases:
  - name: otomi-chart-sops
    installed: true
    namespace: nonexisting
    chart: ../charts/raw
    values:
    - resources:
      - {{- tpl $sopsEnvTpl $v.kms.sops | nindent 8 }}