{{- if .Values.rbac.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "pullsecret-patcher.serviceAccountName" . }}
  labels: {{- include "pullsecret-patcher.labels" . | nindent 4 }}
  {{- with .Values.rbac.annotations }}
  annotations: {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels: {{- include "pullsecret-patcher.labels" . | nindent 4 }}
  name: {{ include "pullsecret-patcher.serviceAccountName" . }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  - serviceaccounts
  verbs:
  - list
  - patch
  - create
  - get
  - delete
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - list
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels: {{- include "pullsecret-patcher.labels" . | nindent 4 }}
  name: {{ include "pullsecret-patcher.serviceAccountName" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "pullsecret-patcher.serviceAccountName" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "pullsecret-patcher.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}    