apiVersion: v1
kind: Secret
type: kubernetes.io/dockerconfigjson
metadata:
  name: {{ include "pullsecret-patcher.fullname" . }}
  labels:
    {{- include "pullsecret-patcher.labels" . | nindent 4 }}
data:
  .dockerconfigjson: {{ include "dockercfg" .Values.registry | b64enc }}
