bases:
  - snippets/defaults.gotmpl
---
{{ readFile "snippets/templates.gotmpl" }}

{{- $v := .Environment.Values }}
{{- $c := $v.charts }}

releases:
  - name: job-ingress-azure
    installed: {{ and (eq $v.cluster.provider "azure") $v.otomi.hasCloudLB (not ($v | get "azure.appgw.isManaged" true)) }}
    <<: *jobs
    labels:
      pkg: ingress-azure
      job: true
  - name: job-harbor
    installed: {{ $c | get "harbor.enabled" false }}
    labels:
      pkg: harbor
      job: true
    <<: *jobs
  - name: job-certs-aws
    installed: {{ and (eq $v.cluster.provider "aws") $v.otomi.hasCloudLB }}
    <<: *jobs
    labels:
      job: true
  - name: job-drone
    installed: false #{{ $c | get "drone.enabled" false }}
    labels:
      pkg: drone
      stage: post
      job: true
    <<: *jobs
  - name: job-gitea-add-users
    installed: {{ $c | get "gitea.enabled" false }}
    labels:
      pkg: gitea
      job: true
    <<: *jobs 