name: Build & perform integration tests

on:
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ${{ matrix.os }} 

    strategy:
        matrix:
          os: [ ubuntu-latest, windows-latest, macos-latest ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2 

    - name: Setup BATS
      run: npm install bats

    - name: Default build & test
      run: |
        npm install && \
        npm run spellcheck && \
        bin/validate-values.sh && \
        bin/validate-templates.sh || true

    - name: Test
      run: bats -r .
    