# yaml-language-server: $schema=https://raw.githubusercontent.com/json-schema-org/json-schema-spec/draft-07/schema.json
name: Integrate helmfile releases
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
env:
  CACHE_REGISTRY: ghcr.io
  CACHE_REPO: redkubes/otomi-core
  REPO: otomi/core
  GIT_USER: redkubesbot
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_OTOMI_TOKEN }}
  KIND_TAG: v1.19.0

jobs:
  kind:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ env.GIT_PASSWORD }}
      - name: Create k8s Kind Cluster
        uses: helm/kind-action@v1.2.0
        continue-on-error: true
      # Important info: https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#docker-container-filesystem
      - name: K8s in Docker
        run: |
          mkdir -p ./env/env
          cp -r ./tests/fixtures/env/ ./env/

          npm ci && \
            npm run compile && \
            /usr/bin/node --experimental-specifier-resolution=node ./dist/otomi.js -- apply
        continue-on-error: true
      - name: Clean up
        run: kind delete cluster --name chart-testing
