# yaml-language-server: $schema=https://raw.githubusercontent.com/json-schema-org/json-schema-spec/draft-07/schema.json
name: Integrate helmfile releases
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '*'
env:
  CACHE_REGISTRY: ghcr.io
  CACHE_REPO: redkubes/otomi-core
  REPO: otomi/core
  GIT_USER: redkubesbot
  GIT_PASSWORD: ${{ secrets.GIT_PASSWORD }}
  DOCKER_PASSWORD: ${{ secrets.DOCKERHUB_OTOMI_TOKEN }}
  KIND_TAG: v1.19.0

jobs:
  kind:
    runs-on: ubuntu-latest
    container:
      image: otomi/tools:kind
      options: --user=root:root
    steps:
      - name: checkout
        uses: actions/checkout@v2
        with:
          token: ${{ env.GIT_PASSWORD }}
      - name: k8s in Docker
        run: |
          export PATH=$PATH:/home/app/tools
          export KUBECONFIG=/root/.kube/config

          kind create cluster --wait 30s \
            --name kind \
            --image kindest/node:${{ env.KIND_TAG }} \
            --config=./kind-config.yaml

          mkdir -p ./env/env
          cp -r ./tests/fixtures/env/ ./env/
          ls -lah ./env/env

          npm ci && \
            npm run compile && \
            /usr/bin/node --experimental-specifier-resolution=node ./dist/otomi.js -- apply

          kind delete cluster --name kind
